export const LIST_KECAMATAN = [
  'Banyuates',
  'Camplong',
  'Jrengik',
  'Karangpenang',
  'Kedungdung',
  'Ketapang',
  'Omben',
  'Pangarengan',
  'Robatal',
  'Sampang',
  'Sokobanah',
  'Sreseh',
  'Tambalengan',
  'Torjun',
]

export const LIST_DESA_BY_KECAMATAN = {
  Banyuates: [
    'Asem Jaran',
    'Banyuates',
    'Batioh',
    'Jatra Timur',
    'Kembang Jeruk',
    'Lar-Lar',
    'Masaran',
    'Montor',
    'Morbatoh',
    'Nagasareh',
    'Nepa',
    'Olor',
    'Planggaran Barat',
    'Planggaran Timur',
    'Tapa"an',
    'Tebanah',
    'Terosan',
    'Tlagah',
    'Tolang',
    'Trapang',
  ],
  Camplong: [
    'Anggersek',
    'Banjar Talela',
    'Banjartabulu',
    'Batukarang',
    'Dharma Camplong',
    'Dharma Tanjung',
    'Madupat',
    'Pamola"an',
    'Plampa"an',
    'PrajjanRabasan',
    'Sejati',
    'Taddan',
    'Tamba"an',
  ],
  Jrengik: [
    'Asemnonggal',
    'Asemraja',
    'Bancelok',
    'Buker',
    'Jrengik',
    'Jungkarang',
    'Kalangan Prao',
    'Kotah',
    'Margantoko',
    'Majangan',
    'Mlakah',
    'Plakaran',
    'Penyepen',
    'Taman',
  ],
  Karangpenang: [
    'Blu uran',
    'Bulmatet',
    'Gunung Kesan',
    'Karangpenang Oloh',
    'Karangpenang Onjur',
    'Poreh',
    'Tlambah',
  ],
  Kedungdung: [
    'Bajrasoka',
    'Banjar',
    'Banyukapah',
    'Batoporo Barat',
    'Batoporo Timur',
    'Daleman',
    'Gunungeleh',
    'Kedungdung',
    'Komis',
    'Kramat',
    'Moktesareh',
    'Nyeloh',
    'Ombul',
    'Pajeruan',
    'Palenggian',
    'Pasarenan',
    'Rabasan',
    'Rohayu',
  ],
  Ketapang: [
    'Banyusokah',
    'Bira Barat',
    'Bunten Barat',
    'Bunten Timur',
    'Karang Anyar',
    'Ketapang Barat',
    'Ketapang Daya',
    'Ketapang Laok',
    'Ketapang Timur',
    'Pancor',
    'Pangereman',
    'Paopale Daya',
    'Paopale Laok',
    'Rabiyan',
  ],
  Omben: [
    'Angsokah',
    'Astapah',
    'Gersempal',
    'Jranguan',
    'Kamondung',
    'Karanggayam',
    'Karangnangger',
    'Kebun Sareh',
    'Madulang',
    'Meteng',
    'Napo Daya',
    'Napo Laok',
    'Omben',
    'Pandan',
    'Rapa Daya',
    'Rapa Laok',
    'Rongdalam',
    'Sogian',
    'Tambak',
    'Temoran',
  ],
  Pangarengan: [
    'Apa an',
    'Gulbung',
    'Pacangga an',
    'Pangarengan',
    'Panyirangan',
    'Ragung',
  ],
  Robatal: [
    'Bapelle',
    'Gunung Rancak',
    'Jelgung',
    'Lepelle',
    'Pandiyangan',
    'Robatal',
    'Sawah Tengah',
    'Torjunan',
    'Tragih',
  ],
  Sampang: [
    // kelurahan
    'Aeng Sareh',
    'Banyumas',
    'Baruh',
    'Gunung Maddah',
    'Kamoning',
    'Pakalongan',
    'Pangelen',
    'Panggung',
    'Paseyan',
    'Pulau Mandangin',
    'Taman Sareh',
    'Tanggumong',
    // desa
    'Banyuanyar',
    'Dalpenang',
    'Gunung Sekar',
    'Karang Dalem',
    'Polagan',
    'Rong Tengah',
  ],
  Sokobanah: [
    'Bira Tengah',
    'Bira Timur',
    'Sokobanah Daya',
    'Sokobanah Laok',
    'Sokobanah Tengah',
    'Tamberu Barat',
    'Tamberu Daya',
    'Tamberu Laok',
    'Tamberu Barat',
    'Tobai Barat',
    'Tobai Tengah',
    'Tobai Timur',
  ],
  Sreseh: [
    'Bangsah',
    'Bundah',
    'Disanah',
    'Junok',
    'Klobur',
    'Labang',
    'Labuhan',
    'Marparan',
    'Noreh',
    'Plasah',
    'Sreseh',
    'Taman',
  ],
  Tambelangan: [
    'Banjarbillah',
    'Barunggagah',
    'Baturasang',
    'Bringin',
    'Birem',
    'Karanganyar',
    'Mambulu Barat',
    'Samaran',
    'Somber',
    'Tambelangan',
  ],
  Torjun: [
    'Bringinnonggal',
    'Dulang',
    'Jeruk Porot',
    'Kanjar',
    'Kara',
    'Kodak',
    'Krampon',
    'Pangongsean',
    'Patapan',
    'Patarongan',
    'Tanah Merah',
    'Torjun',
  ],
}