export const BEARER = 'bearer'
export const INTERNAL_SERVER_ERROR = 'Internal Server Error'
export const INVALID_AUTH = 'invalid auth'
export const PRODUCTION = 'production'
export const SISWA = 'siswa'
export const SEKOLAH = 'sekolah'
export const GURU = 'guru'
